In [81]:
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt

In [82]:
label = np.array(Image.open('/root/master/ATL/dataset/Potsdam_512/Train/label/1.tif'))
label.shape

(512, 512)

In [96]:
def genConfusionMatrix(imgPredict, imgLabel):
    # remove classes from unlabeled pixels in gt image and predict #移除不进行预测的那类
    mask = (imgLabel >= 0) & (imgLabel < 256)   #mask = label>=0&类别数，比如6类，0-5 #判断是否所有像素的标签都在0-6里512*512[True/False]
    label = 255* imgLabel[mask] + imgPredict[mask]  #妙哇，imglabel[mask]，只会显示mask为True的值，并存在以为数组中
    count = np.bincount(label, minlength=256 ** 2) #np.bincount([]),统计[]每个元素有多少种类
    confusionMatrix = count.reshape(256,256)
    return confusionMatrix

In [97]:
label = np.array(Image.open('/root/master/ATL/code/MACUNet/好用的小tools/label.bmp'))
predict = np.array(Image.open('/root/master/ATL/code/MACUNet/好用的小tools/predict.bmp')) 

In [107]:
 np.bincount(label.flatten())

array([2272,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [99]:
conf_mat  = genConfusionMatrix(label,predict)

In [100]:
acc = np.diag(conf_mat)[:-1].sum()/cm[:-1, :-1].sum() #准确度#不算第六6 #不算第6类别

In [102]:
acc_per_class = np.diag(conf_mat) / conf_mat.sum(axis=1)
acc_per_class

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([0.00607639,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        

In [90]:
recall_per_class = np.diag(conf_mat) / conf_mat.sum(axis=0)
recall_per_class

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([0.00220264,        nan,        nan,        nan,        nan,
              nan])

In [103]:
IoU = np.diag(conf_mat) / (conf_mat.sum(axis=1) + conf_mat.sum(axis=0) - np.diag(conf_mat))
mean_IoU = np.nanmean(IoU)
IoU
mean_IoU

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


0.0005523989898989899